- name: Create MariaDB repo file
  template:
    src: mariadb.repo.j2
    dest: /etc/yum.repos.d/mariadb.repo

- name: Update package cache
  dnf:
    name: '*'
    state: latest
  become: true

- name: Install MariaDB server
  dnf:
    name: MariaDB-server
    state: present
  when: ansible_distribution == 'AlmaLinux'