- name: Update MySQL root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_unix_socket: true
  become: true

- name: Remove anonymous MySQL users
  mysql_user:
    name: ""
    host: "{{ item }}"
    state: absent
  with_items:
    - localhost
    - "{{ ansible_hostname }}"
    - 127.0.0.1

- name: Remove test database
  mysql_db:
    name: test
    state: absent

- name: Reload MySQL service
  service:
    name: mysql
    state: reloaded