- name: Create Galera Configuration
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf.d/server.cnf
    owner: root
    group: root
    mode: 0644
    
- name: Stop MySQL on all nodes
  service:
    name: mariadb
    state: stopped
  register: all_stop

- name: Start Galera Cluster on Node 1
  command: galera_new_cluster
  when: inventory_hostname == NODE1_NAME and all_stop is succeeded
  register: galera_result

- name: Wait for Galera Cluster Initialization
  wait_for:
    timeout: 10  # Adjust timeout as needed
  when: inventory_hostname == NODE1_NAME and galera_result is succeeded

- name: Start MySQL on other nodes
  service:
    name: mariadb
    state: started
  when: inventory_hostname != NODE1_NAME

- name: Enable MariaDB service at boot
  service:
    name: mariadb
    enabled: yes