- name: Start Galera Cluster on Node 1
  command: galera_new_cluster
  when: inventory_hostname == node1
  register: galera_result

- name: Wait for Galera Cluster Initialization
  wait_for:
    timeout: 20  # Adjust timeout as needed
  when: inventory_hostname == node1 and galera_result is succeeded

- name: Start MySQL on other nodes
  service:
    name: mariadb
    state: started
  when: inventory_hostname != node1

- name: Enable MariaDB service at boot
  service:
    name: mariadb
    enabled: yes