- name: Setup HAProxy for Three-Node Cluster
  hosts: haproxy_server
  become: true
  gather_facts: true
  tasks:
    - name: Update dnf repositories (for AlmaLinux)
      dnf:
        name: '*'
        state: latest
      when: ansible_distribution == "AlmaLinux"

    - name: Install HAProxy
      dnf:
        name: haproxy
        state: present

    - name: Configure HAProxy
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify:
        - restart haproxy

    - name: Open port 80
      firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled
        immediate: yes

  handlers:
    - name: restart haproxy
      service:
        name: haproxy
        state: restarted