- name: Install MariaDB on AlmaLinux 8
  hosts: galera_nodes
  become: true
  #needed for securing mysql without worrying about installing python on the target node
  roles:
    - geerlingguy.mysql
  vars:
    mysql_bind_address: "{{ ansible_host }}"
    mysql_server_id: "{{ inventory_hostname }}"
    node1: "test-server-el8-1"
    mysql_install_client: false
    mysql_install_server: false
  vars_prompt:
    - name: "mysql_root_password"
      prompt: "Enter the MySQL root password"
      private: yes

  tasks:
    - import_tasks: tasks/install_mariadb.yml
    - import_tasks: tasks/secure_mariadb.yml
    - import_tasks: tasks/configure_firewalld.yml
    - import_tasks: tasks/start_galera_cluster.yml
