- name: Install MariaDB on AlmaLinux 8
  hosts: test_servers
  become: true
  vars:
    mysql_bind_address: "{{ ansible_host }}"
    mysql_server_id: "{{ inventory_hostname }}"
    node1: "test-server-el8-1"

  tasks:
    - name: Create MariaDB repo file
      template:
        src: mariadb.repo.j2
        dest: /etc/yum.repos.d/mariadb.repo
      
    - name: Update package cache
      dnf:
        name: '*'
        state: latest
      become: true

    - name: Install MariaDB server
      dnf:
        name: MariaDB-server
        state: present
      when: ansible_distribution == 'AlmaLinux'

    - name: Create Galera Configuration
      template:
        src: mariadb_server.cnf.j2
        dest: /etc/my.cnf.d/server.cnf

    - name: Start Galera Cluster on Node 1
      command: galera_new_cluster
      when: inventory_hostname == node1
      register: galera_result

    - name: Wait for Galera Cluster Initialization
      wait_for:
        timeout: 300  # Adjust timeout as needed
      when: inventory_hostname == node1 and galera_result is succeeded

    - name: Start MySQL on other nodes
      service:
        name: mariadb
        state: started
      when: inventory_hostname != node1

    - name: Enable MariaDB service at boot
      service:
        name: mariadb
        enabled: yes

