- name: Install MariaDB on AlmaLinux 8
  hosts: galera_nodes
  become: true
  vars_files:
    - vars/vars.yml


  vars_prompt:
    - name: "mysql_user_password"
      prompt: "Enter the MySQL password for {{ mysql_user_name }}"
      private: true

  pre_tasks:
    - name: Generate a random password for the MySQL user
      set_fact:
        mysql_root_password: "{{ lookup('password', '/dev/null length=16') }}"
        
    - import_tasks: tasks/install_mariadb.yml
    - import_tasks: tasks/configure_firewalld.yml

    - name: Override variables for MySQL.
      set_fact:
        mysql_bind_address: "0.0.0.0"
        # mysql_log_error: /var/lib/mysql/mysql.err
        # mysql_pid_file: /var/lib/mysql/mysqld.pid
        # mysql_socket: /var/lib/mysql/mysql.sock
  tasks:
    - import_tasks: tasks/secure_mariadb.yml
    - import_tasks: tasks/start_galera_cluster.yml

  handlers:
    - import_tasks: handlers/main.yml
