- name: Install MariaDB on AlmaLinux 8
  hosts: galera_nodes
  become: true
  #needed for securing mysql without worrying about installing python on the target node
  roles:
    - geerlingguy.mysql
  vars_files:
    - path/to/mysql_vars.yml

  vars_prompt:
    - name: "mysql_root_password"
      prompt: "Enter the MySQL root password"
      private: yes

  pre_tasks:
    - import_tasks: tasks/install_mariadb.yml
    - import_tasks: tasks/configure_firewalld.yml
    - import_tasks: tasks/start_galera_cluster.yml
  tasks:
      - import_tasks: tasks/secure_mariadb.yml

