- name: Install MariaDB on AlmaLinux 8
  hosts: galera_nodes
  become: true
  vars:
    mysql_bind_address: "{{ ansible_host }}"
    mysql_server_id: "{{ inventory_hostname }}"
    node1: "test-server-el8-1"

  tasks:
    - import_tasks: tasks/install_mariadb.yml
    - import_tasks: tasks/secure_mariadb
    - import_tasks: tasks/configure_firewalld.yml
    - import_tasks: tasks/start_galera_cluster.yml
