- name: Install MariaDB on AlmaLinux 8
  hosts: galera_nodes
  become: true
  #needed for securing mysql without worrying about installing python on the target node
  roles:
    - geerlingguy.mysql
  vars_files:
    - vars/vars.yml

  vars_prompt:
    - name: "mysql_root_password"
      prompt: "Enter the MySQL root password"
      private: yes

  pre_tasks:
    - import_tasks: tasks/install_mariadb.yml
    - import_tasks: tasks/configure_firewalld.yml
    - import_tasks: tasks/start_galera_cluster.yml

    - name: Override variables for MySQL.
      set_fact:
        mysql_bind_address: "0.0.0.0"
        mysql_log_error: /var/lib/mysql/mysql/mysql.err
        mysql_pid_file: /var/lib/mysql/mysqld.pid
        mysql_socket: /var/lib/mysql/mysql.sock
  tasks:
    - import_tasks: tasks/secure_mariadb.yml
    - import_tasks: tasks/configure_haproxy.yml